# coding: utf-8

"""
    Customer API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


from fastapi import FastAPI

from customer_api.apis.customer_api import router as CustomerApiRouter
from customer_api.apis.health_api import router as HealthApiRouter

app = FastAPI(
    title="Customer API",
    description="No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)",
    version="1.0",
)

app.include_router(CustomerApiRouter)
app.include_router(HealthApiRouter)
