# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401


class Address(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    Address - a model defined in OpenAPI

        line1: The line1 of this Address.
        line2: The line2 of this Address [Optional].
        city: The city of this Address.
        postcode: The postcode of this Address.
        country: The country of this Address.
    """

    line1: str
    line2: Optional[str] = None
    city: str
    postcode: str
    country: str

Address.update_forward_refs()
