# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401
from customer_api.models.address import Address


class Customer(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    Customer - a model defined in OpenAPI

        id: The id of this Customer [Optional].
        first_name: The first_name of this Customer [Optional].
        surname: The surname of this Customer [Optional].
        dob: The dob of this Customer [Optional].
        primary_address: The primary_address of this Customer [Optional].
    """

    id: Optional[str] = None
    first_name: Optional[str] = None
    surname: Optional[str] = None
    dob: Optional[date] = None
    primary_address: Optional[Dict[str, Any]] = None

Customer.update_forward_refs()
